// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOqc-609kCnTjWj9_JoE-PaOF-q3qk_80',
    appId: '1:541120536910:web:0f8b97bf88e223c36cbe1f',
    messagingSenderId: '541120536910',
    projectId: 'reservation-7fcba',
    authDomain: 'reservation-7fcba.firebaseapp.com',
    storageBucket: 'reservation-7fcba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4jsl6uHs0nsKUQI-AdDFmVQFcdw5NJDg',
    appId: '1:541120536910:android:eb957ead55ddebd66cbe1f',
    messagingSenderId: '541120536910',
    projectId: 'reservation-7fcba',
    storageBucket: 'reservation-7fcba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2FHYiyrgCLHpobncYZ4VF9A35DpAGHj4',
    appId: '1:541120536910:ios:e14c2c64071027966cbe1f',
    messagingSenderId: '541120536910',
    projectId: 'reservation-7fcba',
    storageBucket: 'reservation-7fcba.appspot.com',
    iosBundleId: 'com.example.reservation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2FHYiyrgCLHpobncYZ4VF9A35DpAGHj4',
    appId: '1:541120536910:ios:fc89976b53ea680e6cbe1f',
    messagingSenderId: '541120536910',
    projectId: 'reservation-7fcba',
    storageBucket: 'reservation-7fcba.appspot.com',
    iosBundleId: 'com.example.reservation.RunnerTests',
  );
}
